name: Build ESP32-C3 Firmware (PlatformIO)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pip and PlatformIO
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio
          key: ${{ runner.os }}-pio

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO project
        run: pio run               # 该命令会根据项目根目录下的platformio.ini文件进行构建